---
apiVersion: wyrihaximus.net/v1
kind: RedisDatabase
metadata:
  name: example
spec:
  secret:
    name: example-redis-database
  service:
    read: redis://redis-slave.redis.svc.cluster.local:6379/
    write: redis://redis-master.redis.svc.cluster.local:6379/
---
apiVersion: wyrihaximus.net/v1
kind: RedisDatabase
metadata:
  name: another-example
spec:
  secret:
    name: another-example-redis-database
  service:
    read: redis://redis-slave.redis.svc.cluster.local:6379/
    write: redis://redis-master.redis.svc.cluster.local:6379/
